[package]
name = "svg"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "WASM-based SVG parsing and tessellation using Lyon"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lyon = { workspace = true }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
regex-lite = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
